### ISSUE TITLE
SV3, mute simes, and NEO sims

### ISSUE THREAD

**Issue by ianklatzco** [ianklatzco/uiuc-wendy#1]
from a clubmember
```
You're receiving this email because it affects packs other than my own, so you must reject or approve any changes listed here for them to be effective.

update
all of Mute Sims (particularly 1,7,rejects) as it doesn't look like we have the updates.
Sexuality Violation 3 since there was a non-beta version released
add
N.E.O. Sims (Kigha et al's newest technical pack)

also nice shell script for change game
```

shell script: it's not done yet, workin on it bit by bit when i have downtime at the machine
actually i think currently it might forkbomb the machine (heh oops)
if you have ideas, pls. i'll make a separate issue

please feel free to update mute packs and SV3 — do remove the beta of SV3
 - i think sv2 might be a superset of sv1? so i would imagine SV3 would be the same.
 - i would personally want them sorted into individual packs (eg sv2 on our machine should contain just {SV2's charts}-{SV1's charts} (where {} denotes a set)). if you feel like doing this, please do so. else just put SV3 on the machine and leave it at that (tho, if it is a superset of SV2, please remove SV2)

please feel free to add NEO sims

**Comment by andrewipark** [comment]
I fixed this
closing this ticket
